version: "3.3"
services:
  openai-key:
    build: .
    image: openai-style-api
    command: python open-api.py
    container_name: openai-style-api
    restart: always
    ports:
      - "8090:8090"
    environment:
      - ADMIN-TOKEN=admin
